### ISSUE TITLE
La fonctionalite de recherche

### ISSUE THREAD

**Issue by 4kpros** [donaldoempire1999/open_services_api#1]
Quand tu met query la c'est pour dire quoi ? Donne un exemple voir. Et aussi je met une petite pause d'1 jour pour le rattrapage de compilation.

**Comment by 4kpros** [comment]
Voici le resultat de ma recherche  

_**"error": "Entrez le nom de la collection sur laquelle vous souhaitez faire la recherche**_

**Comment by 4kpros** [comment]
Je passe en parametres ceci : 

`"collection": "publications",
  "query": "web"`

**Comment by donaldoempire1999** [comment]
Je pense que désormais ça va. J'ai fais tout les updates.
